# Generated by Django 5.2.7 on 2025-10-27 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uid',
            new_name='id',
        ),
    ]
