# Generated by Django 5.2.7 on 2025-10-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0002_rename_uid_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid_string',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
