# Generated by Django 5.2.7 on 2025-11-02 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0003_user_uid_string_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_premuim',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('color', models.TextField(choices=[('#FF5733', 'Red'), ('#337AFF', 'Blue'), ('#33FF57', 'Green'), ('#8E33FF', 'Purple'), ('#FF8C33', 'Orange'), ('#FFF333', 'Yellow'), ('#FF33A8', 'Pink'), ('#33FFF3', 'Teal'), ('#A9A9A9', 'Grey')], default='#A9A9A9')),
                ('parent_thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='Discussion.thread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
