# Generated by Django 5.2.7 on 2025-11-05 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0004_blog_is_premuim_thread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='displayName',
        ),
    ]
