# Generated by Django 5.2.7 on 2025-11-05 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0005_remove_user_displayname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uid_string',
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='color',
            field=models.TextField(choices=[('#6366F1', 'Indigo'), ('#10B981', 'Emerald'), ('#F43F5E', 'Rose'), ('#F59E0B', 'Amber'), ('#0EA5E9', 'Sky'), ('#64748B', 'Slate')], default='#64748B'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='parent_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Discussion.thread'),
        ),
    ]
