# Generated by Django 5.2.7 on 2025-11-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0006_remove_user_uid_string_alter_blog_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='Subject',
            field=models.TextField(choices=[('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Maths', 'Maths'), ('Biology', 'Biology'), ('Computer Science', 'Cs'), ('Discussion', 'Discussion')], default='Discussion'),
        ),
    ]
