# Generated by Django 5.2.7 on 2025-11-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0007_thread_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='Subject',
            field=models.TextField(choices=[('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Maths', 'Maths'), ('Biology', 'Biology'), ('Computer Science', 'Cs'), ('General', 'General'), ('Site Feedback', 'Sitefeedback')], default='General'),
        ),
    ]
