# Generated by Django 5.2.7 on 2025-11-09 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0008_alter_thread_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='Subject',
            new_name='subject',
        ),
    ]
